name: 'examples'

on:
  push:

jobs:
  examples:
    name: 'Running examples'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
    - name: Pull container images
      run: |
        docker pull hdlc/sim:osvb
        docker pull hdlc/ghdl:yosys
        docker pull hdlc/nextpnr:ice40
        docker pull hdlc/icestorm
    - run: make -C examples/ghdl sim
    - run: make -C examples/ghdl syn
    - run: make -C examples/impl
